### ISSUE TITLE
时间同步问题是时区问题吗

### ISSUE THREAD

**Issue by gdh1995** [Himself65/Evaluation-of-Y9000X#3]
我遇到过windows 北京时间的话，切到macOS/Ubuntu再切回windows，时间就跳了8小时，网上说是因为保存到cmos里的时间一个是本地时间一个是UTC时间。

如果readme里最后这个问题也是时区问题的话，一种解决办法是把Ubuntu的时区改到冰岛，这样对Win PE最友好，另一种是装一些关机脚本/第三方mac驱动 来自动在开机/关机的时候补偿时间。

**Comment by himself65** [comment]
应该是时区问题，谢谢帮助了
