### ISSUE TITLE
ubuntu19.10  有WIFI吗？

### ISSUE THREAD

**Issue by kangseung** [Himself65/Evaluation-of-Y9000X#7]
据说两大问题在linux上，一个是装完没有WIFI，另外一个是不能外放声音。

另外我看windows有FN+Q调整风扇，在linux下有办法调整转速之类的吗？或者这个和CPU频率有关吗？linux下可以调吗？

谢谢

**Comment by himself65** [comment]
有Wifi、本身自己就会自动调风扇，你要自行控制可以查阅Google
